### ISSUE TITLE
Landing page doesn't feature a short description of gush

### ISSUE THREAD

**Issue by seschwar** [gushphp/gush-site#25]
Wondering what gush might be, I went to its homepage.  However the landing page has absolutely no description whatsoever of what gush could possibly do for me.

Please add at least a short sentence summarizing of why I should bother looking at gush's documentation to find out more.  It would be a waste if people left the site without having a closer look at gush, since it seems very useful.

**Comment by cordoval** [comment]
hi @seschwar thanks for this

do you think you can send us a PR with this line?

what was hard for you to understand gush, would like to get some feedback so we can plug this line

**Comment by cordoval** [comment]
moving to gush due to big merge by @sstok now we can handle central issue repository
